site_name: EHRCON26 Clinical Modelling Workshop
nav:
    - Overview: README.md
    - Getting started: getting-started.md
    - Exercises: exercises.md
theme:
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: lightblue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: lightblue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
markdown_extensions:
    - toc:
        toc_depth: 4
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
extra_css:
    - stylesheets/extra.css